---
# vars file for vsphere-ipi

# Default openshift-install version
openshift_release: "{{ openshift_version | default('stable') }}"

# Working directories
openshift_cluster_dir: "{{ ansible_env.HOME }}/openshift/{{ cluster_name }}"
openshift_cluster_installation_dir: "{{ openshift_cluster_dir }}/installation"

# Default install-config values
num_workers: "{{ workers | default('3') }}"
pod_cidr: "{{ pod_sdn_cidr | default('10.128.0.0/14') }}"
service_cidr: "{{ service_sdn_cidr | default('172.30.0.0/16') }}"
#machine_cidr: '10.0.0.0/16'

# Cluster
cluster_domain: "{{ cluster_name }}.{{ base_domain }}"
api_fqdn: "api.{{ cluster_name }}.{{ base_domain }}"
apps_fqdn: "wildcard.apps.{{ cluster_name }}.{{ base_domain }}"

# OpenShift artifacts
openshift_install_linux: "openshift-install-linux.tar.gz"
openshift_client_linux: "openshift-client-linux.tar.gz"

# install-config secrets
# vCenter Password
vcenter_password: "{{ vault_vcenter_password }}"

# Pull Secret                 
pull_secret_file: "{{ playbook_dir }}/files/{{ pull_secret_name }}"

# Local Registry Certificate
local_registry_certificate: "{{ playbook_dir }}/files/{{ local_registry_cert_name | default(omit) }}"

# Utilities
govc_version: 'v0.25.0'

# Packages
common_packages:
  - python3
  - python3-pip
  - python3-dns
  - python3-pyyaml
  - bash-completion
  - wget
  - curl
  - lsof
  - telnet
  - rsync
  - unzip
  - git
  - tree
  - jq
rpm_packages:
  - bind-utils
  - nmap-ncat
  - nmap
  - vim-enhanced
deb_packages:
  - bind9-dnsutils
  - nmap
  - nmap-common
  - ncat
  - vim
pip_packages:
  - pyvim
  - pyvmomi
  - openshift

