# This is the reference inventory file used by ansible
# for the ocp4-vsphere-ipi project
---
all:
  hosts:
    localhost:
  vars:
    # OpenShift Version
    # Enter desired dotted version '4.7.8'
    # The default version is 'stable'
    openshift_version: 'stable'
    
    # Name of the cluster
    # example: ocp4
    cluster_name: {}
    
    # Parent DNS domain for the cluster
    # example: mydomain.org
    base_domain: {}
    
    # Pull Secret file
    # filename within the files/ dir of this playbook
    pull_secret_name: {}

    # Number of worker nodes to create
    # default: 2
    workers: 2

    # Resources assigned to each worker
    # These are the defaults
    #
    #worker_spec:
    #  cpus: 2
    #  memoryMB: 8196
    #  diskSizeGB: 120
    
    #  Create the cluster with a single master node
    single_master: false
    
    # Resources for the master nodes
    # These are the defaults
    #
    #master_spec:
    #  cpus: 4
    #  memoryMB: 16384
    #  diskSizeGB: 120

    # IP address block for pods
    # This is the default
    pod_cidr: '10.128.0.0/14'

    # IP address block for pods
    # This is the default
    service_cidr: '172.30.0.0/16'

    # IP address block of the nodes
    # example: '10.0.0.0/16'
    machine_cidr: {}

    # IP assigned to the DNS record
    # api.<cluster_name>.<base_domain>
    api_ip: {}
      
    # IP assigned to the DNS record
    # *.apps.<cluster_name>.<base_domain>
    apps_ip: {}

    # IP address of the NTP server
    ntp_ip: {}

    # IP address of the DNS server
    dns_ip: {}

    # Proxy details
    # example: '192.168.1.2:3128'
    proxy_http: {}

    # A comma-separated list of destination domain names, IP addresses,
    # or other network CIDRs to exclude from proxying. Preface a domain
    # with `.` to match subdomains only.
    # example: 'mydomain.com'
    no_proxy_http: {}

    # PEM-encoded X.509 certificate of the proxy
    # In case the proxy has a certificate signed by an authority which RHCOS
    # does not trust by default
    # enter only the file name
    # it should exist in the files/ directory of this playbook
    proxy_cert: {}

    # vCenter Details
    # vcenter_password should be in vault
    vcenter_hostname: {}
    vcenter_username: {}
    vcenter_datacenter: {}
    vcenter_cluster: {}
    vcenter_datastore: {}
    vcenter_network: {}
    # The absolute path of an existing folder where the installer should create VMs
    # If no value is specified, a folder named with the cluster ID will be created
    vcenter_folder: {}
    # The absolute path of an existing resource pool where the installer should create VMs
    # If no value is specified, resources will be installed in the root of the cluster
    vcenter_resource_pool: {}

    # DISCONNECTED
    #
    # IP:port
    local_registry_server: {}

    # Certificate of the local registry
    # enter only the file name
    # the file should exist in the files/ directory of this playbook
    local_registry_cert: {}

    # Registry repository. Example: ocp4/openshift4
    local_registry_repository: {}

    # Paste below the imageContentSources
    # the output obtained from the 'oc adm release mirror'
    #
    #local_registry_sources: |
    #  imageContentSources:
    #  - mirrors:
    #    - local.registry:5000/ocp4/openshift4
    #    source: quay.io/openshift-release-dev/ocp-release
    #  - mirrors:
    #    - local.registry:5000/ocp4/openshift4
    #    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
