---
- name: Get console route
  command: oc --kubeconfig={{ openshift_cluster_installation_dir }}/auth/kubeconfig get route -n openshift-console console -o json
  register: r_console_route
  retries: 10
  delay: 30
  until: r_console_route is succeeded
  ignore_errors: true

- name: Wait for the Install complete message in the install log
  wait_for:
    path: "{{ openshift_cluster_installation_dir }}/.openshift_install.log"
    search_regex: 'Install complete!'

- name: Get output from install log
<<<<<<< HEAD
  command: openshift-install wait-for install-complete --dir={{ openshift_cluster_installation_dir }}
=======
  command: tail -5 {{ openshift_cluster_installation_dir }}/.openshift_install.log
>>>>>>> single-master
  register: r_install_log

- name: Print 
  debug:
<<<<<<< HEAD
    msg: "{{ r_install_log.stdout_lines  }}"
=======
    msg: "{{ r_install_log.stdout_lines  }}"
>>>>>>> single-master
