---
- name: Get console route
  command: oc get route -n openshift-console console -o json
  register: routeconsole
  retries: 10
  delay: 30
  until: routeconsole is succeeded
  ignore_errors: true

- name: Get Webconsole URL
  command: oc whoami --show-console
  register: webconsole_url

- name: Get API URL
  command: oc whoami --show-server
  register: api_url

- name: Print Connection Information
  debug:
    msg: "{{ item }}"
  with_items:
    - "Openshift Master Console: {{ webconsole_url.stdout | trim }}"
    - "Openshift API for command line 'oc' client: {{ api_url.stdout | trim }}"
    - "Openshift access: export KUBECONFIG={{ openshift_cluster_installation_dir }}/auth/kubeconfig"
