- name: "Wait for {{ wait_type }}-complete"
  command: |
    openshift-install wait-for { wait_type }}-complete --dir=/home/{{ ansible_env.USER }}/openshift/{{ cluster_name }}
  async: "{{ 19 * 60 }}"
  poll: 0
  register: wait_for_status

- name: "Check for { wait_type }}-complete status"
  async_status:
    jid: "{{ wait_for_status.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 8
  delay: "{{ 2 * 60}}"
  failed_when: job_result.failed == true and job_result.attempts != 8